dist: trusty
language: java
jdk: oraclejdk8
env:
  - DOCKER_COMPOSE_VERSION=1.4.2

jobs:
  include:
    - stage: build
      script: bash scripts/build.sh
    - stage: prod
      script: bash scripts/artifacting.sh